[package]
name = "bsr"
version = "0.1.0"
authors = ["Ishaan Madan <ishaanmadan2020@u.northwestern.edu>", "David Nelson <davidnelson2019@u.northwestern.edu>", "Alexander Fang <alexanderfang2019@u.northwestern.edu>"]
edition = "2018"

[dependencies]
